version: '2'

services:




  wordpress_app:
    privileged: true
    container_name: wp.dev
    image: wordpress:4.5
    restart: always
    volumes:
      - ./app/themes/html5blank/:/var/www/html/wp-content/themes/html5blank/
    working_dir: '/var/www/html'
    depends_on:
      - mysql_app
    links:
      - mysql_app:mysql
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_HOST: mysql_app:3306

  mysql_app:
    container_name: mysql.dev
    image: mariadb:10.1.16
    ports:
      - 3306:3306
    expose:
      - 3306
    restart: always
    privileged: true
    #volumes:
      # - "./app/database:/var/lib/mysql"
      #- ./app/database/archive:/docker/
    #load in database automaticlly
    #- ./app/database/active:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root


  phpmyadmin_app:
    restart: always
    container_name: phpmyadmin.dev
    depends_on:
      - mysql_app
      - wordpress_app
    links:
      - mysql_app:db
    ports:
      - '8080:80'
    image: phpmyadmin/phpmyadmin:4.6.3-3
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: wordpress
