version: '2'
services:
    custom_wordpress_app:
        build: .
        image: tutum/wordpress:latest
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/dev
        container_name: wp.dev