version: '2'

services:

  wordpress_app:
    privileged: true
    container_name: wp.dev
    image: wordpress:4.5
    restart: always
    volumes:
      - ./app/wp-content/:/var/www/html/wp-content
    working_dir: '/var/www/html'
    links:
    - mysql_app
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: wordpress

  mysql_app:
    container_name: mysql.dev
    image: mariadb:10.1.16
    ports:
      - 3306:3306
    expose:
      - 3306
    restart: always
    privileged: true
    volumes:
    - ./app/database/archive:/docker/
    - ./app/database/active:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root

  phpmyadmin_app:
    restart: always
    container_name: phpmyadmin.dev
    links:
      - mysql_app:db
    ports:
      - '8080:80'
    image: phpmyadmin/phpmyadmin:4.6.3-3
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: wordpress
